// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

// COMPONENT list

lv_obj_t *ui_list_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_list;
    cui_list = lv_obj_create(comp_parent);
    lv_obj_set_height( cui_list, 80);
    lv_obj_set_width( cui_list, lv_pct(100));
    lv_obj_set_align( cui_list, LV_ALIGN_BOTTOM_MID );
    lv_obj_set_flex_flow(cui_list,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_list, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( cui_list, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_radius(cui_list, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_list, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_list, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_list, lv_color_hex(0x446C9E), LV_PART_MAIN | LV_STATE_PRESSED );
    lv_obj_set_style_shadow_opa(cui_list, 255, LV_PART_MAIN| LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(cui_list, 25, LV_PART_MAIN| LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(cui_list, 0, LV_PART_MAIN| LV_STATE_PRESSED);

    lv_obj_t *cui_list_bg_left;
    cui_list_bg_left = lv_img_create(cui_list);
    lv_img_set_src(cui_list_bg_left, &ui_img_text_bg_left_png);
    lv_obj_set_width( cui_list_bg_left, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_list_bg_left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_list_bg_left, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_list_bg_left, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_list_bg_left, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_list_gb_center;
    cui_list_gb_center = lv_img_create(cui_list);
    lv_img_set_src(cui_list_gb_center, &ui_img_text_bg_center_png);
    lv_obj_set_height( cui_list_gb_center, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_flex_grow( cui_list_gb_center, 1);
    lv_obj_set_align( cui_list_gb_center, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_list_gb_center, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_list_gb_center, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_list_bg_right;
    cui_list_bg_right = lv_img_create(cui_list);
    lv_img_set_src(cui_list_bg_right, &ui_img_text_bg_right_png);
    lv_obj_set_width( cui_list_bg_right, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_list_bg_right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_list_bg_right, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_list_bg_right, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_list_bg_right, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_list_content;
    cui_list_content = lv_obj_create(cui_list);
    lv_obj_set_width( cui_list_content, lv_pct(100));
    lv_obj_set_height( cui_list_content, lv_pct(100));
    lv_obj_set_align( cui_list_content, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_list_content, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( cui_list_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_list_content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_list_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_list_content, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_list_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_list_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_list_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_list_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_list_content, 18, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_icon;
    cui_icon = lv_img_create(cui_list_content);
    lv_img_set_src(cui_icon, &ui_img_icn_move_png);
    lv_obj_set_width( cui_icon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_icon, LV_ALIGN_LEFT_MID );
    lv_obj_add_flag( cui_icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_list_label;
    cui_list_label = lv_label_create(cui_list_content);
    lv_obj_set_width( cui_list_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_list_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( cui_list_label, 60 );
    lv_obj_set_y( cui_list_label, 0 );
    lv_obj_set_align( cui_list_label, LV_ALIGN_LEFT_MID );
    lv_label_set_text(cui_list_label,"Move");
    lv_obj_set_style_text_color(cui_list_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_list_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_list_label, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LIST_NUM);
    children[UI_COMP_LIST_LIST] = cui_list;
    children[UI_COMP_LIST_LIST_BG_LEFT] = cui_list_bg_left;
    children[UI_COMP_LIST_LIST_GB_CENTER] = cui_list_gb_center;
    children[UI_COMP_LIST_LIST_BG_RIGHT] = cui_list_bg_right;
    children[UI_COMP_LIST_LIST_CONTENT] = cui_list_content;
    children[UI_COMP_LIST_LIST_CONTENT_ICON] = cui_icon;
    children[UI_COMP_LIST_LIST_CONTENT_LIST_LABEL] = cui_list_label;
    lv_obj_add_event_cb(cui_list, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_list, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_list_create_hook(cui_list);
    return cui_list; 
}

