// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_LIST_H
#define _UI_COMP_LIST_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT list
#define UI_COMP_LIST_LIST 0
#define UI_COMP_LIST_LIST_BG_LEFT 1
#define UI_COMP_LIST_LIST_GB_CENTER 2
#define UI_COMP_LIST_LIST_BG_RIGHT 3
#define UI_COMP_LIST_LIST_CONTENT 4
#define UI_COMP_LIST_LIST_CONTENT_ICON 5
#define UI_COMP_LIST_LIST_CONTENT_LIST_LABEL 6
#define _UI_COMP_LIST_NUM 7
lv_obj_t *ui_list_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
