// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _3D_PRINTER_2_UI_COMP_HOOK_H
#define _3D_PRINTER_2_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Button_create_hook( lv_obj_t *comp );
void ui_comp_bar_group_create_hook( lv_obj_t *comp );
void ui_comp_button_menu_create_hook( lv_obj_t *comp );
void ui_comp_button_print_create_hook( lv_obj_t *comp );
void ui_comp_dot_create_hook( lv_obj_t *comp );
void ui_comp_list_create_hook( lv_obj_t *comp );
void ui_comp_text_bg_group_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
