// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_BUTTON_PRINT_H
#define _UI_COMP_BUTTON_PRINT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT button print
#define UI_COMP_BUTTON_PRINT_BUTTON_PRINT 0
#define UI_COMP_BUTTON_PRINT_LABEL_BUTTON_PRINT 1
#define _UI_COMP_BUTTON_PRINT_NUM 2
lv_obj_t *ui_button_print_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
