// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_BAR_GROUP_H
#define _UI_COMP_BAR_GROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT bar group
#define UI_COMP_BAR_GROUP_BAR_GROUP 0
#define UI_COMP_BAR_GROUP_BAR 1
#define UI_COMP_BAR_GROUP_BAR_TEXT 2
#define UI_COMP_BAR_GROUP_LIMIT 3
#define UI_COMP_BAR_GROUP_LABEL_BAR 4
#define _UI_COMP_BAR_GROUP_NUM 5
lv_obj_t *ui_bar_group_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
