// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_step1_screen_init(void)
{
    ui_step1 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_step1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_flex_flow(ui_step1,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_step1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_img_src( ui_step1, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_header_group = lv_obj_create(ui_step1);
    lv_obj_set_height( ui_header_group, 88);
    lv_obj_set_width( ui_header_group, lv_pct(100));
    lv_obj_set_align( ui_header_group, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_header_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_header_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_header_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_wizard_group = lv_obj_create(ui_header_group);
    lv_obj_set_width( ui_wizard_group, 414);
    lv_obj_set_height( ui_wizard_group, 50);
    lv_obj_set_align( ui_wizard_group, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_wizard_group,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wizard_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_wizard_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_wizard_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_wizard_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_wizard_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_wizard_group, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_dot1 = ui_dot_create(ui_wizard_group);
    lv_obj_set_x( ui_dot1, 0 );
    lv_obj_set_y( ui_dot1, 0 );
    lv_obj_add_state( ui_dot1, LV_STATE_CHECKED );     /// States

    ui_line1 = lv_obj_create(ui_wizard_group);
    lv_obj_set_width( ui_line1, 100);
    lv_obj_set_height( ui_line1, 3);
    lv_obj_set_align( ui_line1, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_line1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_line1, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_line1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line1, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
    lv_obj_set_style_bg_opa(ui_line1, 255, LV_PART_MAIN| LV_STATE_CHECKED);

    ui_dot2 = ui_dot_create(ui_wizard_group);
    lv_obj_set_x( ui_dot2, 0 );
    lv_obj_set_y( ui_dot2, 0 );

    lv_label_set_text(ui_comp_get_child(ui_dot2, UI_COMP_DOT_LABEL_DOT),"2");

    ui_line2 = lv_obj_create(ui_wizard_group);
    lv_obj_set_width( ui_line2, 100);
    lv_obj_set_height( ui_line2, 3);
    lv_obj_set_align( ui_line2, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_line2, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_line2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line2, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
    lv_obj_set_style_bg_opa(ui_line2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

    ui_dot3 = ui_dot_create(ui_wizard_group);
    lv_obj_set_x( ui_dot3, 0 );
    lv_obj_set_y( ui_dot3, 0 );

    lv_label_set_text(ui_comp_get_child(ui_dot3, UI_COMP_DOT_LABEL_DOT),"3");

    ui_content_group = lv_obj_create(ui_step1);
    lv_obj_set_width( ui_content_group, lv_pct(100));
    lv_obj_set_flex_grow( ui_content_group, 1);
    lv_obj_set_align( ui_content_group, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_content_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_text_group = lv_obj_create(ui_content_group);
    lv_obj_set_width( ui_content_text_group, lv_pct(62));
    lv_obj_set_height( ui_content_text_group, lv_pct(100));
    lv_obj_set_align( ui_content_text_group, LV_ALIGN_LEFT_MID );
    lv_obj_set_flex_flow(ui_content_text_group,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_text_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_content_text_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_text_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_text_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_text_group, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_text_group, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_text_group, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_text_group, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_text_group, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_text_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_content_text_group);
    lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_Label1,"Heading");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_content_text_group);
    lv_obj_set_width( ui_Label2, lv_pct(100));
    lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_Label2,"Before calibrating the printer, the head and bed must be heated to the appropriate temperature. Only after this can the calibration process begin.");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_temp_group = lv_obj_create(ui_content_group);
    lv_obj_set_width( ui_content_temp_group, 304);
    lv_obj_set_height( ui_content_temp_group, lv_pct(100));
    lv_obj_set_align( ui_content_temp_group, LV_ALIGN_RIGHT_MID );
    lv_obj_set_flex_flow(ui_content_temp_group,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_temp_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_content_temp_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_temp_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_temp_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_temp_group, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_temp_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_text_bg_group = ui_text_bg_group_create(ui_content_temp_group);
    lv_obj_set_x( ui_text_bg_group, 0 );
    lv_obj_set_y( ui_text_bg_group, 0 );

    ui_text_bg_group1 = ui_text_bg_group_create(ui_content_temp_group);
    lv_obj_set_x( ui_text_bg_group1, 0 );
    lv_obj_set_y( ui_text_bg_group1, 0 );

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group1, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL1),"65°");

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group1, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL2),"/ 65°");

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group1, UI_COMP_TEXT_BG_GROUP_TEXT_BG_LABEL3),"Bed teperature");

    ui_separator = lv_img_create(ui_content_group);
    lv_img_set_src(ui_separator, &ui_img_separetor_png);
    lv_obj_set_width( ui_separator, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_separator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_separator, 90 );
    lv_obj_set_y( ui_separator, 0 );
    lv_obj_set_align( ui_separator, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_separator, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( ui_separator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_footer_group = lv_obj_create(ui_step1);
    lv_obj_set_height( ui_footer_group, 96);
    lv_obj_set_width( ui_footer_group, lv_pct(100));
    lv_obj_set_align( ui_footer_group, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_footer_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_footer_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_footer_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Button = ui_Button_create(ui_footer_group);
    lv_obj_set_x( ui_Button, 0 );
    lv_obj_set_y( ui_Button, 0 );

    lv_obj_add_event_cb(ui_Button, ui_event_Button_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_step1, ui_event_step1, LV_EVENT_ALL, NULL);

}
