// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_step3_screen_init(void)
{
    ui_step3 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_step3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_flex_flow(ui_step3,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_step3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_img_src( ui_step3, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_step3_bg = lv_img_create(ui_step3);
    lv_img_set_src(ui_step3_bg, &ui_img_step3_bg_png);
    lv_obj_set_width( ui_step3_bg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_step3_bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_step3_bg, LV_ALIGN_RIGHT_MID );
    lv_obj_add_flag( ui_step3_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( ui_step3_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_arrow = lv_img_create(ui_step3);
    lv_img_set_src(ui_arrow, &ui_img_arrow_png);
    lv_obj_set_width( ui_arrow, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_arrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_arrow, 159 );
    lv_obj_set_y( ui_arrow, -94 );
    lv_obj_set_align( ui_arrow, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_arrow, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( ui_arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_header_group2 = lv_obj_create(ui_step3);
    lv_obj_set_height( ui_header_group2, 88);
    lv_obj_set_width( ui_header_group2, lv_pct(100));
    lv_obj_set_align( ui_header_group2, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_header_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_header_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_header_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_wizard_group2 = lv_obj_create(ui_header_group2);
    lv_obj_set_width( ui_wizard_group2, 414);
    lv_obj_set_height( ui_wizard_group2, 50);
    lv_obj_set_align( ui_wizard_group2, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_wizard_group2,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wizard_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_wizard_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_wizard_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_wizard_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_wizard_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_wizard_group2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_dot7 = ui_dot_create(ui_wizard_group2);
    lv_obj_set_x( ui_dot7, 0 );
    lv_obj_set_y( ui_dot7, 0 );
    lv_obj_clear_state( ui_dot7, LV_STATE_CHECKED );   /// States

    lv_obj_clear_flag( ui_comp_get_child(ui_dot7, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN );    /// Flags

    lv_obj_clear_flag( ui_comp_get_child(ui_dot7, UI_COMP_DOT_READY), LV_OBJ_FLAG_HIDDEN );    /// Flags

    ui_line5 = lv_obj_create(ui_wizard_group2);
    lv_obj_set_width( ui_line5, 100);
    lv_obj_set_height( ui_line5, 3);
    lv_obj_set_align( ui_line5, LV_ALIGN_CENTER );
    lv_obj_add_state( ui_line5, LV_STATE_CHECKED );     /// States
    lv_obj_clear_flag( ui_line5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_line5, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_line5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line5, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
    lv_obj_set_style_bg_opa(ui_line5, 255, LV_PART_MAIN| LV_STATE_CHECKED);

    ui_dot8 = ui_dot_create(ui_wizard_group2);
    lv_obj_set_x( ui_dot8, 0 );
    lv_obj_set_y( ui_dot8, 0 );

    lv_label_set_text(ui_comp_get_child(ui_dot8, UI_COMP_DOT_LABEL_DOT),"2");

    lv_obj_clear_flag( ui_comp_get_child(ui_dot8, UI_COMP_DOT_READY_BG), LV_OBJ_FLAG_HIDDEN );    /// Flags

    lv_obj_clear_flag( ui_comp_get_child(ui_dot8, UI_COMP_DOT_READY), LV_OBJ_FLAG_HIDDEN );    /// Flags

    ui_line6 = lv_obj_create(ui_wizard_group2);
    lv_obj_set_width( ui_line6, 100);
    lv_obj_set_height( ui_line6, 3);
    lv_obj_set_align( ui_line6, LV_ALIGN_CENTER );
    lv_obj_add_state( ui_line6, LV_STATE_CHECKED );     /// States
    lv_obj_clear_flag( ui_line6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_line6, lv_color_hex(0x373648), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_line6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_line6, lv_color_hex(0x4EBE4B), LV_PART_MAIN | LV_STATE_CHECKED );
    lv_obj_set_style_bg_opa(ui_line6, 255, LV_PART_MAIN| LV_STATE_CHECKED);

    ui_dot9 = ui_dot_create(ui_wizard_group2);
    lv_obj_set_x( ui_dot9, 0 );
    lv_obj_set_y( ui_dot9, 0 );
    lv_obj_add_state( ui_dot9, LV_STATE_CHECKED );     /// States

    lv_label_set_text(ui_comp_get_child(ui_dot9, UI_COMP_DOT_LABEL_DOT),"3");

    ui_content_group2 = lv_obj_create(ui_step3);
    lv_obj_set_width( ui_content_group2, lv_pct(100));
    lv_obj_set_flex_grow( ui_content_group2, 1);
    lv_obj_set_align( ui_content_group2, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_content_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_text_group2 = lv_obj_create(ui_content_group2);
    lv_obj_set_width( ui_content_text_group2, lv_pct(62));
    lv_obj_set_height( ui_content_text_group2, lv_pct(100));
    lv_obj_set_align( ui_content_text_group2, LV_ALIGN_LEFT_MID );
    lv_obj_set_flex_flow(ui_content_text_group2,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_text_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_content_text_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_text_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_text_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_text_group2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_text_group2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_text_group2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_text_group2, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_text_group2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_text_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_content_text_group2);
    lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_Label5,"Include filament");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_content_text_group2);
    lv_obj_set_width( ui_Label6, lv_pct(100));
    lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_Label6,"Calibration has been successfully completed. Insert the filament according to the instructions.");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_footer_group2 = lv_obj_create(ui_step3);
    lv_obj_set_height( ui_footer_group2, 96);
    lv_obj_set_width( ui_footer_group2, lv_pct(100));
    lv_obj_set_align( ui_footer_group2, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_footer_group2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_footer_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_footer_group2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Button2 = ui_Button_create(ui_footer_group2);
    lv_obj_set_x( ui_Button2, 0 );
    lv_obj_set_y( ui_Button2, 0 );

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_step3, ui_event_step3, LV_EVENT_ALL, NULL);

}
