// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_TEXT_BG_GROUP_H
#define _UI_COMP_TEXT_BG_GROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT text bg group
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_GROUP 0
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG 1
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_BG_LEFT 2
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_GB_CENTER 3
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_BG_RIGHT 4
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT 5
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL1 6
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL2 7
#define UI_COMP_TEXT_BG_GROUP_TEXT_BG_LABEL3 8
#define _UI_COMP_TEXT_BG_GROUP_NUM 9
lv_obj_t *ui_text_bg_group_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
