// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

// COMPONENT text bg group

lv_obj_t *ui_text_bg_group_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_text_bg_group;
    cui_text_bg_group = lv_obj_create(comp_parent);
    lv_obj_set_width( cui_text_bg_group, 220);
    lv_obj_set_height( cui_text_bg_group, 110);
    lv_obj_set_align( cui_text_bg_group, LV_ALIGN_CENTER );
    lv_obj_clear_flag( cui_text_bg_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_text_bg_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_text_bg_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_text_bg;
    cui_text_bg = lv_obj_create(cui_text_bg_group);
    lv_obj_set_height( cui_text_bg, 80);
    lv_obj_set_width( cui_text_bg, lv_pct(100));
    lv_obj_set_align( cui_text_bg, LV_ALIGN_BOTTOM_MID );
    lv_obj_set_flex_flow(cui_text_bg,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_text_bg, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( cui_text_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_text_bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_text_bg, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_tx_bg_left;
    cui_tx_bg_left = lv_img_create(cui_text_bg);
    lv_img_set_src(cui_tx_bg_left, &ui_img_text_bg_left_png);
    lv_obj_set_width( cui_tx_bg_left, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_tx_bg_left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_tx_bg_left, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_tx_bg_left, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_tx_bg_left, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_tx_gb_center;
    cui_tx_gb_center = lv_img_create(cui_text_bg);
    lv_img_set_src(cui_tx_gb_center, &ui_img_text_bg_center_png);
    lv_obj_set_height( cui_tx_gb_center, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_flex_grow( cui_tx_gb_center, 1);
    lv_obj_set_align( cui_tx_gb_center, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_tx_gb_center, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_tx_gb_center, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_tx_bg_right;
    cui_tx_bg_right = lv_img_create(cui_text_bg);
    lv_img_set_src(cui_tx_bg_right, &ui_img_text_bg_right_png);
    lv_obj_set_width( cui_tx_bg_right, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_tx_bg_right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_tx_bg_right, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_tx_bg_right, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_tx_bg_right, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_text_bg_content;
    cui_text_bg_content = lv_obj_create(cui_text_bg);
    lv_obj_set_width( cui_text_bg_content, lv_pct(100));
    lv_obj_set_height( cui_text_bg_content, lv_pct(100));
    lv_obj_set_align( cui_text_bg_content, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(cui_text_bg_content,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_text_bg_content, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag( cui_text_bg_content, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( cui_text_bg_content, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_text_bg_content, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_text_bg_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_text_bg_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_text_bg_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_text_bg_content, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_text_bg_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_text_bg_content, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_text_bg_content, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_text_bg_label1;
    cui_text_bg_label1 = lv_label_create(cui_text_bg_content);
    lv_obj_set_width( cui_text_bg_label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_text_bg_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_text_bg_label1, LV_ALIGN_CENTER );
    lv_label_set_text(cui_text_bg_label1,"210°");
    lv_obj_set_style_text_color(cui_text_bg_label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_text_bg_label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_text_bg_label1, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_text_bg_label2;
    cui_text_bg_label2 = lv_label_create(cui_text_bg_content);
    lv_obj_set_width( cui_text_bg_label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_text_bg_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_text_bg_label2, LV_ALIGN_CENTER );
    lv_label_set_text(cui_text_bg_label2,"/ 210°");
    lv_obj_set_style_text_color(cui_text_bg_label2, lv_color_hex(0x87888D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_text_bg_label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_text_bg_label2, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_text_bg_label3;
    cui_text_bg_label3 = lv_label_create(cui_text_bg_group);
    lv_obj_set_width( cui_text_bg_label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_text_bg_label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( cui_text_bg_label3, LV_ALIGN_TOP_MID );
    lv_label_set_text(cui_text_bg_label3,"Head teperature");
    lv_obj_set_style_text_color(cui_text_bg_label3, lv_color_hex(0x87888D), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_text_bg_label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_text_bg_label3, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TEXT_BG_GROUP_NUM);
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_GROUP] = cui_text_bg_group;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG] = cui_text_bg;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_BG_LEFT] = cui_tx_bg_left;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_GB_CENTER] = cui_tx_gb_center;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TX_BG_RIGHT] = cui_tx_bg_right;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT] = cui_text_bg_content;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL1] = cui_text_bg_label1;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL2] = cui_text_bg_label2;
    children[UI_COMP_TEXT_BG_GROUP_TEXT_BG_LABEL3] = cui_text_bg_label3;
    lv_obj_add_event_cb(cui_text_bg_group, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_text_bg_group, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_text_bg_group_create_hook(cui_text_bg_group);
    return cui_text_bg_group; 
}

