// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

// COMPONENT bar group

lv_obj_t *ui_bar_group_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_bar_group;
    cui_bar_group = lv_obj_create(comp_parent);
    lv_obj_set_width( cui_bar_group, 91);
    lv_obj_set_height( cui_bar_group, 409);
    lv_obj_set_align( cui_bar_group, LV_ALIGN_BOTTOM_MID );
    lv_obj_clear_flag( cui_bar_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_bar_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_bar_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_bar;
    cui_bar = lv_bar_create(cui_bar_group);
    lv_bar_set_value(cui_bar,90,LV_ANIM_OFF);
    lv_obj_set_width( cui_bar, 25);
    lv_obj_set_height( cui_bar, 324);
    lv_obj_set_x( cui_bar, 0 );
    lv_obj_set_y( cui_bar, -10 );
    lv_obj_set_align( cui_bar, LV_ALIGN_CENTER );
    lv_obj_set_style_radius(cui_bar, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_bar, lv_color_hex(0x201C29), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(cui_bar, lv_color_hex(0x34354E), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_outline_opa(cui_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(cui_bar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_bar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_bar, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_bar, lv_color_hex(0x956DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_bar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_bar, lv_color_hex(0x088DFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_grad_dir(cui_bar, LV_GRAD_DIR_VER, LV_PART_INDICATOR| LV_STATE_DEFAULT);

    lv_obj_t *cui_bar_text;
    cui_bar_text = lv_img_create(cui_bar_group);
    lv_img_set_src(cui_bar_text, &ui_img_headtemp_png);
    lv_obj_set_width( cui_bar_text, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_bar_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( cui_bar_text, -6 );
    lv_obj_set_y( cui_bar_text, -62 );
    lv_obj_set_align( cui_bar_text, LV_ALIGN_BOTTOM_RIGHT );
    lv_obj_add_flag( cui_bar_text, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( cui_bar_text, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_t *cui_limit;
    cui_limit = lv_obj_create(cui_bar_group);
    lv_obj_set_width( cui_limit, 20);
    lv_obj_set_height( cui_limit, 2);
    lv_obj_set_x( cui_limit, -3 );
    lv_obj_set_y( cui_limit, 65 );
    lv_obj_set_align( cui_limit, LV_ALIGN_TOP_RIGHT );
    lv_obj_clear_flag( cui_limit, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_limit, lv_color_hex(0x41445A), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_limit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t *cui_label_bar;
    cui_label_bar = lv_label_create(cui_bar_group);
    lv_obj_set_width( cui_label_bar, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_label_bar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( cui_label_bar, 2 );
    lv_obj_set_y( cui_label_bar, -20 );
    lv_obj_set_align( cui_label_bar, LV_ALIGN_BOTTOM_MID );
    lv_label_set_text(cui_label_bar,"210°");
    lv_obj_set_style_text_color(cui_label_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_label_bar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_label_bar, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BAR_GROUP_NUM);
    children[UI_COMP_BAR_GROUP_BAR_GROUP] = cui_bar_group;
    children[UI_COMP_BAR_GROUP_BAR] = cui_bar;
    children[UI_COMP_BAR_GROUP_BAR_TEXT] = cui_bar_text;
    children[UI_COMP_BAR_GROUP_LIMIT] = cui_limit;
    children[UI_COMP_BAR_GROUP_LABEL_BAR] = cui_label_bar;
    lv_obj_add_event_cb(cui_bar_group, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_bar_group, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_bar_group_create_hook(cui_bar_group);
    return cui_bar_group; 
}

