// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_BUTTON_MENU_H
#define _UI_COMP_BUTTON_MENU_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT button menu
#define UI_COMP_BUTTON_MENU_BUTTON_MENU 0
#define UI_COMP_BUTTON_MENU_LABEL_GROUP 1
#define UI_COMP_BUTTON_MENU_LABEL_GROUP_LABEL_MENU_BUTTON 2
#define UI_COMP_BUTTON_MENU_ICN_GROUP 3
#define UI_COMP_BUTTON_MENU_ICN_GROUP_ICN_MENU_BUTTON 4
#define _UI_COMP_BUTTON_MENU_NUM 5
lv_obj_t *ui_button_menu_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
