// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_main_menu_screen_init(void)
{
    ui_main_menu = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_main_menu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_main_menu, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_header_group3 = lv_obj_create(ui_main_menu);
    lv_obj_set_height( ui_header_group3, 88);
    lv_obj_set_width( ui_header_group3, lv_pct(100));
    lv_obj_set_align( ui_header_group3, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_header_group3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_header_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_header_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_header_group3);
    lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label7, LV_ALIGN_LEFT_MID );
    lv_label_set_text(ui_Label7,"Main menu");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_pos_group = lv_obj_create(ui_header_group3);
    lv_obj_set_width( ui_pos_group, lv_pct(50));
    lv_obj_set_height( ui_pos_group, lv_pct(100));
    lv_obj_set_align( ui_pos_group, LV_ALIGN_RIGHT_MID );
    lv_obj_set_flex_flow(ui_pos_group,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pos_group, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_pos_group, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_pos_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_pos_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_posx = lv_obj_create(ui_pos_group);
    lv_obj_set_width( ui_posx, 100);
    lv_obj_set_height( ui_posx, 50);
    lv_obj_set_align( ui_posx, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_posx,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_posx, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_posx, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_posx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_posx, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_posx, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_posx, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_x = lv_label_create(ui_posx);
    lv_obj_set_width( ui_label_x, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_x, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_x, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_x,"X");
    lv_obj_set_style_text_color(ui_label_x, lv_color_hex(0x7B7D83), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_x, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_x, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_x1 = lv_label_create(ui_posx);
    lv_obj_set_width( ui_label_x1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_x1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_x1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_x1,"130.0");
    lv_obj_set_style_text_color(ui_label_x1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_x1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_x1, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_posy = lv_obj_create(ui_pos_group);
    lv_obj_set_width( ui_posy, 100);
    lv_obj_set_height( ui_posy, 50);
    lv_obj_set_align( ui_posy, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_posy,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_posy, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_posy, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_posy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_posy, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_posy, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_posy, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_y = lv_label_create(ui_posy);
    lv_obj_set_width( ui_label_y, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_y, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_y, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_y,"Y");
    lv_obj_set_style_text_color(ui_label_y, lv_color_hex(0x7B7D83), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_y, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_y, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_y2 = lv_label_create(ui_posy);
    lv_obj_set_width( ui_label_y2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_y2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_y2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_y2,"78.2");
    lv_obj_set_style_text_color(ui_label_y2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_y2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_y2, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_posz = lv_obj_create(ui_pos_group);
    lv_obj_set_width( ui_posz, 100);
    lv_obj_set_height( ui_posz, 50);
    lv_obj_set_align( ui_posz, LV_ALIGN_CENTER );
    lv_obj_set_flex_flow(ui_posz,LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_posz, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_posz, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_posz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_posz, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_posz, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_posz, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_z1 = lv_label_create(ui_posz);
    lv_obj_set_width( ui_label_z1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_z1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_z1, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_z1,"X");
    lv_obj_set_style_text_color(ui_label_z1, lv_color_hex(0x7B7D83), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_z1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_z1, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_label_z2 = lv_label_create(ui_posz);
    lv_obj_set_width( ui_label_z2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_z2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_z2, LV_ALIGN_CENTER );
    lv_label_set_text(ui_label_z2,"112.8");
    lv_obj_set_style_text_color(ui_label_z2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_z2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_z2, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_group3 = lv_obj_create(ui_main_menu);
    lv_obj_set_height( ui_content_group3, 272);
    lv_obj_set_width( ui_content_group3, lv_pct(100));
    lv_obj_set_x( ui_content_group3, 0 );
    lv_obj_set_y( ui_content_group3, -25 );
    lv_obj_set_align( ui_content_group3, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_content_group3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_group3, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_group3, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_button_menu_print = ui_button_menu_create(ui_content_group3);
    lv_obj_set_x( ui_button_menu_print, 0 );
    lv_obj_set_y( ui_button_menu_print, 0 );
    lv_obj_set_align( ui_button_menu_print, LV_ALIGN_LEFT_MID );

    lv_obj_set_x( ui_comp_get_child(ui_button_menu_print, UI_COMP_BUTTON_MENU_ICN_GROUP), 10 );
    lv_obj_set_y( ui_comp_get_child(ui_button_menu_print, UI_COMP_BUTTON_MENU_ICN_GROUP), -25 );

    ui_button_menu_settings = ui_button_menu_create(ui_content_group3);
    lv_obj_set_x( ui_button_menu_settings, 0 );
    lv_obj_set_y( ui_button_menu_settings, 0 );
    lv_obj_set_align( ui_button_menu_settings, LV_ALIGN_CENTER );

    lv_label_set_text(ui_comp_get_child(ui_button_menu_settings, UI_COMP_BUTTON_MENU_LABEL_GROUP_LABEL_MENU_BUTTON),"Setup");

    lv_obj_set_x( ui_comp_get_child(ui_button_menu_settings, UI_COMP_BUTTON_MENU_ICN_GROUP), 10 );
    lv_obj_set_y( ui_comp_get_child(ui_button_menu_settings, UI_COMP_BUTTON_MENU_ICN_GROUP), -25 );

    lv_img_set_src(ui_comp_get_child(ui_button_menu_settings, UI_COMP_BUTTON_MENU_ICN_GROUP_ICN_MENU_BUTTON), &ui_img_icn_settings_png);

    ui_button_control_control = ui_button_menu_create(ui_content_group3);
    lv_obj_set_x( ui_button_control_control, 0 );
    lv_obj_set_y( ui_button_control_control, 0 );
    lv_obj_set_align( ui_button_control_control, LV_ALIGN_RIGHT_MID );

    lv_label_set_text(ui_comp_get_child(ui_button_control_control, UI_COMP_BUTTON_MENU_LABEL_GROUP_LABEL_MENU_BUTTON),"Calibration");

    lv_img_set_src(ui_comp_get_child(ui_button_control_control, UI_COMP_BUTTON_MENU_ICN_GROUP_ICN_MENU_BUTTON), &ui_img_icn_control_png);

    ui_footer_group3 = lv_obj_create(ui_main_menu);
    lv_obj_set_height( ui_footer_group3, 162);
    lv_obj_set_width( ui_footer_group3, lv_pct(100));
    lv_obj_set_align( ui_footer_group3, LV_ALIGN_BOTTOM_MID );
    lv_obj_clear_flag( ui_footer_group3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_footer_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_footer_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_footer_group3, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_footer_group3, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_footer_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_footer_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_text_bg_group3 = ui_text_bg_group_create(ui_footer_group3);
    lv_obj_set_x( ui_text_bg_group3, 0 );
    lv_obj_set_y( ui_text_bg_group3, 0 );
    lv_obj_set_align( ui_text_bg_group3, LV_ALIGN_LEFT_MID );

    ui_text_bg_group2 = ui_text_bg_group_create(ui_footer_group3);
    lv_obj_set_x( ui_text_bg_group2, 0 );
    lv_obj_set_y( ui_text_bg_group2, 0 );

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group2, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL1),"65°");

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group2, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL2),"/ 65°");

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group2, UI_COMP_TEXT_BG_GROUP_TEXT_BG_LABEL3),"Bed teperature");

    ui_text_bg_group4 = ui_text_bg_group_create(ui_footer_group3);
    lv_obj_set_x( ui_text_bg_group4, 0 );
    lv_obj_set_y( ui_text_bg_group4, 0 );
    lv_obj_set_align( ui_text_bg_group4, LV_ALIGN_RIGHT_MID );

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group4, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL1),"100%");

    lv_obj_add_flag( ui_comp_get_child(ui_text_bg_group4, UI_COMP_TEXT_BG_GROUP_TEXT_BG_TEXT_BG_CONTENT_TEXT_BG_LABEL2), LV_OBJ_FLAG_HIDDEN );   /// Flags

    lv_label_set_text(ui_comp_get_child(ui_text_bg_group4, UI_COMP_TEXT_BG_GROUP_TEXT_BG_LABEL3),"Fan speed");

    lv_obj_add_event_cb(ui_button_menu_print, ui_event_button_menu_print_button_menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_menu_settings, ui_event_button_menu_settings_button_menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_button_control_control, ui_event_button_control_control_button_menu, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_main_menu, ui_event_main_menu, LV_EVENT_ALL, NULL);

}
