// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_final_screen_init(void)
{
    ui_final = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_final, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_img_src( ui_final, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_pad_left(ui_final, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_final, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_final, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_final, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_image_printer = lv_img_create(ui_final);
    lv_img_set_src(ui_image_printer, &ui_img_print_ready_png);
    lv_obj_set_width( ui_image_printer, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_image_printer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_image_printer, 0 );
    lv_obj_set_y( ui_image_printer, -15 );
    lv_obj_set_align( ui_image_printer, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_image_printer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_image_printer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_Button4 = ui_Button_create(ui_final);
    lv_obj_set_x( ui_Button4, 0 );
    lv_obj_set_y( ui_Button4, 0 );

    lv_label_set_text(ui_comp_get_child(ui_Button4, UI_COMP_BUTTON_LABEL_BUTTON),"Ready");

    ui_label_ready = lv_label_create(ui_final);
    lv_obj_set_width( ui_label_ready, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_label_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_label_ready, LV_ALIGN_TOP_MID );
    lv_label_set_text(ui_label_ready,"Ready to print");
    lv_obj_set_style_text_color(ui_label_ready, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_label_ready, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_ready, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_ok_group = lv_obj_create(ui_final);
    lv_obj_set_width( ui_ok_group, 394);
    lv_obj_set_height( ui_ok_group, 335);
    lv_obj_set_x( ui_ok_group, -100 );
    lv_obj_set_y( ui_ok_group, 0 );
    lv_obj_set_align( ui_ok_group, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_ok_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_ok_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_ok_group, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_image_ok_big = lv_img_create(ui_ok_group);
    lv_img_set_src(ui_image_ok_big, &ui_img_ok_big_png);
    lv_obj_set_width( ui_image_ok_big, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_image_ok_big, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_image_ok_big, LV_ALIGN_CENTER );
    lv_obj_add_flag( ui_image_ok_big, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_image_ok_big, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_final, ui_event_final, LV_EVENT_ALL, NULL);

}
