// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_flex_flow(ui_settings,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_img_src( ui_settings, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_settings_bg = lv_img_create(ui_settings);
    lv_img_set_src(ui_settings_bg, &ui_img_bg_settings_png);
    lv_obj_set_width( ui_settings_bg, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_settings_bg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_settings_bg, LV_ALIGN_RIGHT_MID );
    lv_obj_add_flag( ui_settings_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( ui_settings_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_header_group6 = lv_obj_create(ui_settings);
    lv_obj_set_height( ui_header_group6, 100);
    lv_obj_set_width( ui_header_group6, lv_pct(100));
    lv_obj_set_align( ui_header_group6, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_header_group6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_header_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_header_group6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_settings_label = lv_label_create(ui_header_group6);
    lv_obj_set_width( ui_settings_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_settings_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_settings_label, LV_ALIGN_CENTER );
    lv_label_set_text(ui_settings_label,"Settings");
    lv_obj_set_style_text_color(ui_settings_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_settings_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_label, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_back_button = lv_btn_create(ui_header_group6);
    lv_obj_set_width( ui_back_button, 100);
    lv_obj_set_height( ui_back_button, 70);
    lv_obj_set_align( ui_back_button, LV_ALIGN_LEFT_MID );
    lv_obj_add_flag( ui_back_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
    lv_obj_clear_flag( ui_back_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_back_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_back_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_back = lv_img_create(ui_back_button);
    lv_img_set_src(ui_back, &ui_img_icn_back_png);
    lv_obj_set_width( ui_back, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( ui_back, 36 );
    lv_obj_set_y( ui_back, 0 );
    lv_obj_set_align( ui_back, LV_ALIGN_LEFT_MID );
    lv_obj_add_flag( ui_back, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
    lv_obj_clear_flag( ui_back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_content_group6 = lv_obj_create(ui_settings);
    lv_obj_set_height( ui_content_group6, 380);
    lv_obj_set_width( ui_content_group6, lv_pct(100));
    lv_obj_set_align( ui_content_group6, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_content_group6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_group6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_text_group4 = lv_obj_create(ui_content_group6);
    lv_obj_set_width( ui_content_text_group4, lv_pct(62));
    lv_obj_set_height( ui_content_text_group4, lv_pct(100));
    lv_obj_set_align( ui_content_text_group4, LV_ALIGN_LEFT_MID );
    lv_obj_set_flex_flow(ui_content_text_group4,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_text_group4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_content_text_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_text_group4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_text_group4, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_text_group4, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_text_group4, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_text_group4, 18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_text_group4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_text_group4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_content_text_group4, lv_color_hex(0x58586C), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_text_group4, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

    ui_list = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list, 0 );
    lv_obj_set_y( ui_list, 0 );

    ui_list1 = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list1, 0 );
    lv_obj_set_y( ui_list1, 0 );

    lv_img_set_src(ui_comp_get_child(ui_list1, UI_COMP_LIST_LIST_CONTENT_ICON), &ui_img_icn_disable_png);

    lv_label_set_text(ui_comp_get_child(ui_list1, UI_COMP_LIST_LIST_CONTENT_LIST_LABEL),"Disable Steppers");

    ui_list2 = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list2, 0 );
    lv_obj_set_y( ui_list2, 0 );

    lv_img_set_src(ui_comp_get_child(ui_list2, UI_COMP_LIST_LIST_CONTENT_ICON), &ui_img_icn_home_png);

    lv_label_set_text(ui_comp_get_child(ui_list2, UI_COMP_LIST_LIST_CONTENT_LIST_LABEL),"Auto Home");

    ui_list3 = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list3, 0 );
    lv_obj_set_y( ui_list3, 0 );

    lv_img_set_src(ui_comp_get_child(ui_list3, UI_COMP_LIST_LIST_CONTENT_ICON), &ui_img_icn_zoffset_png);

    lv_label_set_text(ui_comp_get_child(ui_list3, UI_COMP_LIST_LIST_CONTENT_LIST_LABEL),"Z-Offset");

    ui_list4 = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list4, 0 );
    lv_obj_set_y( ui_list4, 0 );

    lv_img_set_src(ui_comp_get_child(ui_list4, UI_COMP_LIST_LIST_CONTENT_ICON), &ui_img_icn_filament_png);

    lv_label_set_text(ui_comp_get_child(ui_list4, UI_COMP_LIST_LIST_CONTENT_LIST_LABEL),"Preload PLA");

    ui_list5 = ui_list_create(ui_content_text_group4);
    lv_obj_set_x( ui_list5, 0 );
    lv_obj_set_y( ui_list5, 0 );

    lv_img_set_src(ui_comp_get_child(ui_list5, UI_COMP_LIST_LIST_CONTENT_ICON), &ui_img_icn_filament_png);

    lv_label_set_text(ui_comp_get_child(ui_list5, UI_COMP_LIST_LIST_CONTENT_LIST_LABEL),"Preload ABS");

    lv_obj_add_event_cb(ui_back_button, ui_event_back_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);

}
