// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#ifndef _UI_COMP_DOT_H
#define _UI_COMP_DOT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dot
#define UI_COMP_DOT_DOT 0
#define UI_COMP_DOT_LABEL_DOT 1
#define UI_COMP_DOT_READY_BG 2
#define UI_COMP_DOT_READY 3
#define _UI_COMP_DOT_NUM 4
lv_obj_t *ui_dot_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
