// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

// COMPONENT button print

lv_obj_t *ui_button_print_create(lv_obj_t *comp_parent) {

    lv_obj_t *cui_button_print;
    cui_button_print = lv_btn_create(comp_parent);
    lv_obj_set_width( cui_button_print, 118);
    lv_obj_set_height( cui_button_print, 96);
    lv_obj_set_align( cui_button_print, LV_ALIGN_CENTER );
    lv_obj_add_flag( cui_button_print, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
    lv_obj_clear_flag( cui_button_print, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(cui_button_print, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(cui_button_print, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( cui_button_print, &ui_img_btn3_png, LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_color(cui_button_print, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(cui_button_print, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_button_print, &ui_font_Title, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src( cui_button_print, &ui_img_btn3_press_png, LV_PART_MAIN | LV_STATE_PRESSED );
    lv_obj_set_style_text_color(cui_button_print, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
    lv_obj_set_style_text_opa(cui_button_print, 255, LV_PART_MAIN| LV_STATE_PRESSED);

    lv_obj_t *cui_label_button_print;
    cui_label_button_print = lv_label_create(cui_button_print);
    lv_obj_set_width( cui_label_button_print, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( cui_label_button_print, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x( cui_label_button_print, 0 );
    lv_obj_set_y( cui_label_button_print, -10 );
    lv_obj_set_align( cui_label_button_print, LV_ALIGN_CENTER );
    lv_label_set_text(cui_label_button_print,"Pause");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_PRINT_NUM);
    children[UI_COMP_BUTTON_PRINT_BUTTON_PRINT] = cui_button_print;
    children[UI_COMP_BUTTON_PRINT_LABEL_BUTTON_PRINT] = cui_label_button_print;
    lv_obj_add_event_cb(cui_button_print, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_button_print, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_button_print_create_hook(cui_button_print);
    return cui_button_print; 
}

