LV_IMG_DECLARE(ui_img__status_battery_1_png);
LV_IMG_DECLARE(ui_img__status_battery_2_png);
LV_IMG_DECLARE(ui_img__status_battery_3_png);
LV_IMG_DECLARE(ui_img__status_battery_4_png);
LV_IMG_DECLARE(ui_img__status_battery_5_png);

LV_IMG_DECLARE(ui_img__status_charging_1_png);
LV_IMG_DECLARE(ui_img__status_charging_2_png);
LV_IMG_DECLARE(ui_img__status_charging_3_png);
LV_IMG_DECLARE(ui_img__status_charging_4_png);
LV_IMG_DECLARE(ui_img__status_charging_5_png);