// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: 3d_Printer_2

#include "../ui.h"

void ui_welcome_screen_init(void)
{
    ui_welcome = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_welcome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_flex_flow(ui_welcome,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_welcome, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_img_src( ui_welcome, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT );

    ui_printer_in = lv_img_create(ui_welcome);
    lv_img_set_src(ui_printer_in, &ui_img_anim_printer_in_01_png);
    lv_obj_set_width( ui_printer_in, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_printer_in, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_printer_in, LV_ALIGN_RIGHT_MID );
    lv_obj_add_flag( ui_printer_in, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
    lv_obj_clear_flag( ui_printer_in, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    ui_header_group5 = lv_obj_create(ui_welcome);
    lv_obj_set_height( ui_header_group5, 100);
    lv_obj_set_width( ui_header_group5, lv_pct(100));
    lv_obj_set_align( ui_header_group5, LV_ALIGN_CENTER );
    lv_obj_clear_flag( ui_header_group5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_header_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_header_group5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_header_group5);
    lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
    lv_label_set_text(ui_Label9,"Welcome");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_H1, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_group5 = lv_obj_create(ui_welcome);
    lv_obj_set_width( ui_content_group5, lv_pct(100));
    lv_obj_set_flex_grow( ui_content_group5, 1);
    lv_obj_set_align( ui_content_group5, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_content_group5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_group5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_text_group3 = lv_obj_create(ui_content_group5);
    lv_obj_set_width( ui_content_text_group3, lv_pct(62));
    lv_obj_set_height( ui_content_text_group3, lv_pct(100));
    lv_obj_set_align( ui_content_text_group3, LV_ALIGN_LEFT_MID );
    lv_obj_set_flex_flow(ui_content_text_group3,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_text_group3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag( ui_content_text_group3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_text_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_text_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_content_text_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_content_text_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_content_text_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_content_text_group3, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_text_group3, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_text_group3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_content_text_group3);
    lv_obj_set_width( ui_Label10, lv_pct(100));
    lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_label_set_text(ui_Label10,"Congratulations on your new SquareLine printer! With this printer, you can achieve anything your imagination desires.\n\nPress the Calibration button to set up the device.");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label10, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Subtitle, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_content_temp_group1 = lv_obj_create(ui_content_group5);
    lv_obj_set_width( ui_content_temp_group1, 304);
    lv_obj_set_height( ui_content_temp_group1, lv_pct(100));
    lv_obj_set_align( ui_content_temp_group1, LV_ALIGN_RIGHT_MID );
    lv_obj_set_flex_flow(ui_content_temp_group1,LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_content_temp_group1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag( ui_content_temp_group1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_content_temp_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_content_temp_group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_content_temp_group1, 40, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_content_temp_group1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_footer_group4 = lv_obj_create(ui_welcome);
    lv_obj_set_height( ui_footer_group4, 96);
    lv_obj_set_width( ui_footer_group4, lv_pct(100));
    lv_obj_set_align( ui_footer_group4, LV_ALIGN_TOP_MID );
    lv_obj_clear_flag( ui_footer_group4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
    lv_obj_set_style_bg_color(ui_footer_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_footer_group4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_Button3 = ui_Button_create(ui_footer_group4);
    lv_obj_set_x( ui_Button3, 0 );
    lv_obj_set_y( ui_Button3, 0 );

    lv_label_set_text(ui_comp_get_child(ui_Button3, UI_COMP_BUTTON_LABEL_BUTTON),"Calibration");

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_welcome, ui_event_welcome, LV_EVENT_ALL, NULL);

}
